# Generated by Django 4.2.25 on 2025-10-07 23:14

from django.db import migrations

def create_initial_roles_and_permissions(apps, schema_editor):

    # Grab the models
    Roles = apps.get_model('djangoProject', 'Roles')
    Permissions = apps.get_model('djangoProject', 'Permissions')
    PermissionMap = apps.get_model('djangoProject', 'PermissionMap')

    # Create the roles
    basic_role, _ = Roles.objects.get_or_create(role_name='basic user')
    admin_role, _ = Roles.objects.get_or_create(role_name='admin user')

    # Create the permissions
    create_markets, _ = Permissions.objects.get_or_create(permission_name="create_markets") # Example - as not too sure what further permissions needed

    # Map the permissions to the role
    
        # ADMIN PERMS
    PermissionMap.objects.get_or_create(role=admin_role, permission=create_markets)

def delete_initial_roles_and_permissions(apps, schema_editor):
    Roles = apps.get_model('djangoProject', 'Roles')
    Permissions = apps.get_model('djangoProject', 'Permissions')

    Roles.objects.all().delete()
    Permissions.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_roles_and_permissions,
            delete_initial_roles_and_permissions
        )
    ]
