# Generated by Django 4.2.25 on 2025-10-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0003_remove_profiles_email_token_emailtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
