# Generated by Django 4.2.25 on 2025-10-10 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0004_alter_emailtoken_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='side',
            new_name='share_type',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='maker_order',
            new_name='maker_order_id',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='taker_order',
            new_name='taker_order_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4),
        ),
        migrations.AddField(
            model_name='orders',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cancellation_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('FILLED', 'Filled'), ('PARTIALLY_FILLED', 'Partially Filled'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
