# Generated by Django 4.2.25 on 2025-10-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0005_rename_side_orders_share_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='positions',
            unique_together={('event', 'user', 'side')},
        ),
    ]
