# Generated by Django 4.2.25 on 2025-10-26 05:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0006_alter_positions_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='winning_outcome',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='positions',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='positions',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='positions',
            name='winnings_paid',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20),
        ),
    ]
