# Generated by Django 4.2.25 on 2025-10-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0007_events_settled_events_settled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
